//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bywhoEntities : DbContext
    {
        public bywhoEntities()
            : base("name=bywhoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Styles> Styles { get; set; }
        public virtual DbSet<Topic> Topic { get; set; }
        public virtual DbSet<Resources> Resources { get; set; }
        public virtual DbSet<CartLines> CartLines { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<Sizes> Sizes { get; set; }
        public virtual DbSet<Picture> Picture { get; set; }
        public virtual DbSet<Customercarts> Customercarts { get; set; }
        public virtual DbSet<Materials> Materials { get; set; }
    }
}
