//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Picture
    {
        public System.Guid Id { get; set; }
        public string Path { get; set; }
        public Nullable<System.Guid> CartLineId { get; set; }
        public Nullable<System.Guid> OrderLineId { get; set; }
    
        public virtual CartLines CartLines { get; set; }
    }
}
